/*5*/
--PROCEDURES
DROP PROCEDURE BOOKTABLE;
DROP PROCEDURE ADDPHONE;
DROP PROCEDURE ADDTABLESCATEGORY;
DROP PROCEDURE TABLEREMOVE;
--FUNCTIONS
DROP FUNCTION TABLEEXISTS;
DROP FUNCTION TABLERESERVED;
--DROP FUNCTION CALCULATEBILL;
--DROP FUNCTION CLIENTMONEYPAIDYEAR;
--TRIGGERS
DROP TRIGGER CAPITALCUSTTRIGGER;
DROP TRIGGER CAPITALSERVTRIGGER;
DROP TRIGGER HOURTRIGGER;
DROP TRIGGER MONTHTRIGGER;
DROP TRIGGER TABLEBOOKTIMESTRIGGER;
DROP TRIGGER CATEGORYTABLESCOUNTTRIGGER;
--DROP TRIGGER RESERVATIONBILLTRIGGER;